### ISSUE TITLE
Not work again same issue

### ISSUE THREAD

**Issue by piyushbest** [ItzLightyHD/SkyBlockUI#1]
I tap in menu button no response not something like it's plugin not have commands

**Comment by LightSwagitzHD** [comment]
Which issue

**Comment by LightSwagitzHD** [comment]
You need to have SkyBlock plugin by GiantQuartz
Otherwhise will not work

**Comment by piyushbest** [comment]
Dude sorry it's not problem I added shopGUI and gui+uI = unstable I removed
gui it's work xD can u work on EnchantShopUI u have to fix my EnchantShopUI
I m busy on other project so u can do that thx and sorry for noob issue

**Comment by LightSwagitzHD** [comment]
Ok, but not today, I’m busy today and i have to do in my server, in my yt channel and to play with my friends.
